services:
  discord-bot:
    build: .
    container_name: wm-discord-bot
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - PUID=${PUID} # ホストのユーザーIDを渡す
      - PGID=${PGID} # ホストのグループIDを渡す
    volumes:
      - .:/app
    restart: always
    user: "${PUID}:${PGID}" # ユーザーとグループをホスト側と一致させる