services:
  discord-bot:
    build: .
    container_name: watermark-discord-bot-1
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - BASE_DIR=${BASE_DIR}
    volumes:
      - .:/app
    restart: always
