services:
  discord-bot:
    build: .
    container_name: wm-discord-bot
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - PUID=1000
      - PGID=1000
    volumes:
      - .:/app
    restart: always
